### ISSUE TITLE
Add support for OpenAPI 3.1 

### ISSUE THREAD

**Issue by omarudolley** [koxudaxi/datamodel-code-generator#1649]

**Comment by joakimnordling** [comment]
I could add that to my understanding generation of models still works if you just disable the validation of the OpenAPI spec, but the validation of OpenAPI 3.1 specs fails due to `prance` not supporting it. The corresponding issue in `prance`: [Support for open api v3.1 #95](https://github.com/RonnyPfannschmidt/prance/issues/95).

**Comment by koxudaxi** [comment]
@joakimnordling 
Thank you for your comment
I have released a fixed version  [0.24.0](https://github.com/koxudaxi/datamodel-code-generator/releases/tag/0.24.0)
The version deprecated `--validation` option and changed related options like prance to optional.

@omarudolley 
I just closed the option. if you have any problem with OpenAPI 3.1. please re-open or create a new issue with the details.
