### ISSUE TITLE
Add ability to use generic container types

### ISSUE THREAD

**Issue by ofek** [koxudaxi/datamodel-code-generator#334]
**Is your feature request related to a problem? Please describe.**

We have immutability requirements and therefore do not use `list`/`typing.List` nor `dict`/`typing.Dict`

**Describe the solution you'd like**

An option that would use `typing.Sequence` instead of `typing.List` and `typing.Mapping` instead of `typing.Dict`

If `use_standard_collections` option is set, then import from `collections.abc` instead of `typing`

**Describe alternatives you've considered**

In my feature branch I have a post-generation step that modifies the output file

**Additional context**

Soon, every [Datadog Agent integration](https://github.com/DataDog/integrations-core) will use this to generate models for user configuration 🙂

**Comment by koxudaxi** [comment]
@ofek 
Thank you for suggesting this feature.
Looks Good!!
I will implement it when I get the time.

> Soon, every Datadog Agent integration will use this to generate models for user configuration 🙂

Wow, it's excellent news. 🥳 
May I write the use-case in the README/documentation after you release it?

**Comment by ofek** [comment]
> May I write the use-case in the README/documentation after you release it?

Sure!

**Comment by koxudaxi** [comment]
@ofek 
I have released a new version `0.7.3` 
The version has `--use-generic-container-types`

**Comment by ofek** [comment]
Amazing, thank you very much!!! I'll comment here when my PR gets merged 🙂

**Comment by ofek** [comment]
https://github.com/DataDog/integrations-core/pull/8675 is merged and I've started the syncing of every integration: https://github.com/DataDog/integrations-core/pulls 😄

**Comment by koxudaxi** [comment]
@ofek 
It's great!! 🎉 

Do you use OpenAPIParser directly here?
https://github.com/DataDog/integrations-core/blob/85d693ffa317c20c7e623a17c299e6ea137a5a35/datadog_checks_dev/datadog_checks/dev/tooling/specs/configuration/consumers/model.py

I will keep the result of OpenAPIParser().parse().
But, I will refactor the low-level function because the current version doesn't reach `1.0`
If you get any problem, then please tell me it.
Also, I can add unittest or integration test to your project.  

Thank you

**Comment by ofek** [comment]
Yes we use that directly. I'll let you know if we encounter any issues, thank you!

**Comment by ofek** [comment]
https://datadoghq.dev/integrations-core/meta/config-models/
